version: 2

models:
  - name: orders
    description: "Demo orders model"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer
        tests:
          - not_null
      - name: amount
        tests:
          - not_null
          - accepted_values:
              values: [100, 120, 150, 175, 180, 200, 210, 250, 300, 90]